version: '3'
services:
   mongodb:
     image: mongo
     container_name: mongodb
     restart: "always"
     ports: 
         - "27017:27017"
     volumes:
      - /Users/vikaspatel/Documents/databases/mongodb/festival:/data/db   
   backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./
    container_name: backend
    restart: always  
    ports:
      - "5001:5001"
    env_file:
      - .env 
    volumes:
      - .:/backend
      - node_modules 
      - /frontend  
    depends_on:
      - mongodb
   frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000" 
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend        